// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rtp/v1/rtp.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotOptWeightsState int32

const (
	SlotOptWeightsState_SLOT_OPT_WEIGHTS_STATE_UNSPECIFIED SlotOptWeightsState = 0
	SlotOptWeightsState_SLOT_OPT_WEIGHTS_STATE_NOT_FOUND   SlotOptWeightsState = 1 // 无权重缓存
	SlotOptWeightsState_SLOT_OPT_WEIGHTS_STATE_TRAINING    SlotOptWeightsState = 2 // 训练中（持锁）
	SlotOptWeightsState_SLOT_OPT_WEIGHTS_STATE_READY       SlotOptWeightsState = 3 // 已就绪
)

// Enum value maps for SlotOptWeightsState.
var (
	SlotOptWeightsState_name = map[int32]string{
		0: "SLOT_OPT_WEIGHTS_STATE_UNSPECIFIED",
		1: "SLOT_OPT_WEIGHTS_STATE_NOT_FOUND",
		2: "SLOT_OPT_WEIGHTS_STATE_TRAINING",
		3: "SLOT_OPT_WEIGHTS_STATE_READY",
	}
	SlotOptWeightsState_value = map[string]int32{
		"SLOT_OPT_WEIGHTS_STATE_UNSPECIFIED": 0,
		"SLOT_OPT_WEIGHTS_STATE_NOT_FOUND":   1,
		"SLOT_OPT_WEIGHTS_STATE_TRAINING":    2,
		"SLOT_OPT_WEIGHTS_STATE_READY":       3,
	}
)

func (x SlotOptWeightsState) Enum() *SlotOptWeightsState {
	p := new(SlotOptWeightsState)
	*p = x
	return p
}

func (x SlotOptWeightsState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotOptWeightsState) Descriptor() protoreflect.EnumDescriptor {
	return file_rtp_v1_rtp_proto_enumTypes[0].Descriptor()
}

func (SlotOptWeightsState) Type() protoreflect.EnumType {
	return &file_rtp_v1_rtp_proto_enumTypes[0]
}

func (x SlotOptWeightsState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotOptWeightsState.Descriptor instead.
func (SlotOptWeightsState) EnumDescriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{0}
}

type SelectSpinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                             //商户
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`                       //账号id
	GameBrand     string                 `protobuf:"bytes,3,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                     //游戏厂商
	GameId        string                 `protobuf:"bytes,4,opt,name=gameId,proto3" json:"gameId,omitempty"`                           //游戏id
	Bet           float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                               //下注
	RoundModel    string                 `protobuf:"bytes,6,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT,EXTRA,BUY
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Mock          string                 `protobuf:"bytes,8,opt,name=mock,proto3" json:"mock,omitempty"`
	RoundExtModel string                 `protobuf:"bytes,9,opt,name=round_ext_model,json=roundExtModel,proto3" json:"round_ext_model,omitempty"` // 扩展模式.BUY的填值[1, 2, 3],EXTRA的填[1.5, 3]
	SpinId        int64                  `protobuf:"varint,10,opt,name=spinId,proto3" json:"spinId,omitempty"`                                    //指定本局spin样本id
	SpinTableName string                 `protobuf:"bytes,11,opt,name=spinTableName,proto3" json:"spinTableName,omitempty"`                       //指定本局spin样本表名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectSpinRequest) Reset() {
	*x = SelectSpinRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSpinRequest) ProtoMessage() {}

func (x *SelectSpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSpinRequest.ProtoReflect.Descriptor instead.
func (*SelectSpinRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{0}
}

func (x *SelectSpinRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SelectSpinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SelectSpinRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SelectSpinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SelectSpinRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SelectSpinRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *SelectSpinRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SelectSpinRequest) GetMock() string {
	if x != nil {
		return x.Mock
	}
	return ""
}

func (x *SelectSpinRequest) GetRoundExtModel() string {
	if x != nil {
		return x.RoundExtModel
	}
	return ""
}

func (x *SelectSpinRequest) GetSpinId() int64 {
	if x != nil {
		return x.SpinId
	}
	return 0
}

func (x *SelectSpinRequest) GetSpinTableName() string {
	if x != nil {
		return x.SpinTableName
	}
	return ""
}

type SelectSpinReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpinId         int64                  `protobuf:"varint,1,opt,name=spinId,proto3" json:"spinId,omitempty"`      //spin样本id
	GameBrand      string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId         string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	Bet            float64                `protobuf:"fixed64,4,opt,name=bet,proto3" json:"bet,omitempty"`           //下注
	OriginBet      float64                `protobuf:"fixed64,5,opt,name=originBet,proto3" json:"originBet,omitempty"`
	OriginTotalWin float64                `protobuf:"fixed64,6,opt,name=originTotalWin,proto3" json:"originTotalWin,omitempty"`
	Data           []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                               // spin数据
	RoundModel     string                 `protobuf:"bytes,8,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT,EXTRA,BUY
	TableName      string                 `protobuf:"bytes,9,opt,name=tableName,proto3" json:"tableName,omitempty"`                     //本次表名
	Rtp            string                 `protobuf:"bytes,10,opt,name=rtp,proto3" json:"rtp,omitempty"`                                // 本次rtp档位
	Rate           float64                `protobuf:"fixed64,11,opt,name=rate,proto3" json:"rate,omitempty"`                            // 本次spin的概率
	Compress       int32                  `protobuf:"varint,12,opt,name=compress,proto3" json:"compress,omitempty"`                     // 压缩数据
	NextId         int64                  `protobuf:"varint,13,opt,name=nextId,proto3" json:"nextId,omitempty"`                         // 下一个样本id
	GroupId        string                 `protobuf:"bytes,14,opt,name=groupId,proto3" json:"groupId,omitempty"`                        // 分组id
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SelectSpinReply) Reset() {
	*x = SelectSpinReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSpinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSpinReply) ProtoMessage() {}

func (x *SelectSpinReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSpinReply.ProtoReflect.Descriptor instead.
func (*SelectSpinReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{1}
}

func (x *SelectSpinReply) GetSpinId() int64 {
	if x != nil {
		return x.SpinId
	}
	return 0
}

func (x *SelectSpinReply) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SelectSpinReply) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SelectSpinReply) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SelectSpinReply) GetOriginBet() float64 {
	if x != nil {
		return x.OriginBet
	}
	return 0
}

func (x *SelectSpinReply) GetOriginTotalWin() float64 {
	if x != nil {
		return x.OriginTotalWin
	}
	return 0
}

func (x *SelectSpinReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SelectSpinReply) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *SelectSpinReply) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SelectSpinReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *SelectSpinReply) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *SelectSpinReply) GetCompress() int32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *SelectSpinReply) GetNextId() int64 {
	if x != nil {
		return x.NextId
	}
	return 0
}

func (x *SelectSpinReply) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetPlayerRtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`   //账号id
	GameBrand     string                 `protobuf:"bytes,3,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,4,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRtpRequest) Reset() {
	*x = GetPlayerRtpRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRtpRequest) ProtoMessage() {}

func (x *GetPlayerRtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRtpRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRtpRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRtpRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetPlayerRtpRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetPlayerRtpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtp           string                 `protobuf:"bytes,1,opt,name=rtp,proto3" json:"rtp,omitempty"` // 本次rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRtpReply) Reset() {
	*x = GetPlayerRtpReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRtpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRtpReply) ProtoMessage() {}

func (x *GetPlayerRtpReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRtpReply.ProtoReflect.Descriptor instead.
func (*GetPlayerRtpReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerRtpReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type GetBaccaratRtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	RoundId       string                 `protobuf:"bytes,4,opt,name=roundId,proto3" json:"roundId,omitempty"`     // 局id
	Rtp           string                 `protobuf:"bytes,5,opt,name=rtp,proto3" json:"rtp,omitempty"`             // rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratRtpRequest) Reset() {
	*x = GetBaccaratRtpRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratRtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratRtpRequest) ProtoMessage() {}

func (x *GetBaccaratRtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratRtpRequest.ProtoReflect.Descriptor instead.
func (*GetBaccaratRtpRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{4}
}

func (x *GetBaccaratRtpRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetBaccaratRtpRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type GetBaccaratRtpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtp           string                 `protobuf:"bytes,1,opt,name=rtp,proto3" json:"rtp,omitempty"`       // rtp档位
	Rate1         float64                `protobuf:"fixed64,2,opt,name=rate1,proto3" json:"rate1,omitempty"` // 1倍爆率
	Rate2         float64                `protobuf:"fixed64,3,opt,name=rate2,proto3" json:"rate2,omitempty"` // >=2倍爆率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaccaratRtpReply) Reset() {
	*x = GetBaccaratRtpReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaccaratRtpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaccaratRtpReply) ProtoMessage() {}

func (x *GetBaccaratRtpReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaccaratRtpReply.ProtoReflect.Descriptor instead.
func (*GetBaccaratRtpReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{5}
}

func (x *GetBaccaratRtpReply) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *GetBaccaratRtpReply) GetRate1() float64 {
	if x != nil {
		return x.Rate1
	}
	return 0
}

func (x *GetBaccaratRtpReply) GetRate2() float64 {
	if x != nil {
		return x.Rate2
	}
	return 0
}

type SettleBaccaratRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`                         //商户
	GameBrand        string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                 //游戏厂商
	GameId           string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`                       //游戏id
	RoundBetTotal    float64                `protobuf:"fixed64,4,opt,name=roundBetTotal,proto3" json:"roundBetTotal,omitempty"`       //本局下注总额
	RoundProfitTotal float64                `protobuf:"fixed64,5,opt,name=roundProfitTotal,proto3" json:"roundProfitTotal,omitempty"` //本局平台本次盈利
	RoundId          string                 `protobuf:"bytes,6,opt,name=roundId,proto3" json:"roundId,omitempty"`                     // 局id
	Rtp              string                 `protobuf:"bytes,7,opt,name=rtp,proto3" json:"rtp,omitempty"`                             // rtp档位
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SettleBaccaratRequest) Reset() {
	*x = SettleBaccaratRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBaccaratRequest) ProtoMessage() {}

func (x *SettleBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBaccaratRequest.ProtoReflect.Descriptor instead.
func (*SettleBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{6}
}

func (x *SettleBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *SettleBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetRoundBetTotal() float64 {
	if x != nil {
		return x.RoundBetTotal
	}
	return 0
}

func (x *SettleBaccaratRequest) GetRoundProfitTotal() float64 {
	if x != nil {
		return x.RoundProfitTotal
	}
	return 0
}

func (x *SettleBaccaratRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SettleBaccaratRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type SettleBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleBaccaratReply) Reset() {
	*x = SettleBaccaratReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBaccaratReply) ProtoMessage() {}

func (x *SettleBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBaccaratReply.ProtoReflect.Descriptor instead.
func (*SettleBaccaratReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{7}
}

type ResetBaccaratRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`         //商户
	GameBrand     string                 `protobuf:"bytes,2,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"` //游戏厂商
	GameId        string                 `protobuf:"bytes,3,opt,name=gameId,proto3" json:"gameId,omitempty"`       //游戏id
	Rtp           string                 `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"`             // rtp档位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBaccaratRequest) Reset() {
	*x = ResetBaccaratRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBaccaratRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBaccaratRequest) ProtoMessage() {}

func (x *ResetBaccaratRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBaccaratRequest.ProtoReflect.Descriptor instead.
func (*ResetBaccaratRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{8}
}

func (x *ResetBaccaratRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ResetBaccaratRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *ResetBaccaratRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ResetBaccaratRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

type ResetBaccaratReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBaccaratReply) Reset() {
	*x = ResetBaccaratReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBaccaratReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBaccaratReply) ProtoMessage() {}

func (x *ResetBaccaratReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBaccaratReply.ProtoReflect.Descriptor instead.
func (*ResetBaccaratReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{9}
}

type RefreshSlotOptWeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameBrand     string                 `protobuf:"bytes,1,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                     // 游戏厂商
	GameId        string                 `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`                           // 游戏 id
	RoundModel    string                 `protobuf:"bytes,3,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT, EXTRA, BUY
	Rtp           string                 `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"`                                 // rtp 档位，如 "97"
	Bet           float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                               // jili bet 分档游戏需传 bet，其他可传 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSlotOptWeightsRequest) Reset() {
	*x = RefreshSlotOptWeightsRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSlotOptWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSlotOptWeightsRequest) ProtoMessage() {}

func (x *RefreshSlotOptWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSlotOptWeightsRequest.ProtoReflect.Descriptor instead.
func (*RefreshSlotOptWeightsRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshSlotOptWeightsRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *RefreshSlotOptWeightsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RefreshSlotOptWeightsRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *RefreshSlotOptWeightsRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *RefreshSlotOptWeightsRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

type RefreshSlotOptWeightsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheKey      string                 `protobuf:"bytes,1,opt,name=cacheKey,proto3" json:"cacheKey,omitempty"` // 写入 Redis 的权重缓存 key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSlotOptWeightsReply) Reset() {
	*x = RefreshSlotOptWeightsReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSlotOptWeightsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSlotOptWeightsReply) ProtoMessage() {}

func (x *RefreshSlotOptWeightsReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSlotOptWeightsReply.ProtoReflect.Descriptor instead.
func (*RefreshSlotOptWeightsReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshSlotOptWeightsReply) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

type VerifySlotOptWeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameBrand     string                 `protobuf:"bytes,1,opt,name=gameBrand,proto3" json:"gameBrand,omitempty"`                     // 游戏厂商
	GameId        string                 `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`                           // 游戏 id
	RoundModel    string                 `protobuf:"bytes,3,opt,name=round_model,json=roundModel,proto3" json:"round_model,omitempty"` // 模式: DEFAULT, EXTRA, BUY
	Rtp           string                 `protobuf:"bytes,4,opt,name=rtp,proto3" json:"rtp,omitempty"`                                 // rtp 档位，如 "97"
	Bet           float64                `protobuf:"fixed64,5,opt,name=bet,proto3" json:"bet,omitempty"`                               // jili bet 分档游戏需传 bet，其他可传 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySlotOptWeightsRequest) Reset() {
	*x = VerifySlotOptWeightsRequest{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySlotOptWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySlotOptWeightsRequest) ProtoMessage() {}

func (x *VerifySlotOptWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySlotOptWeightsRequest.ProtoReflect.Descriptor instead.
func (*VerifySlotOptWeightsRequest) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{12}
}

func (x *VerifySlotOptWeightsRequest) GetGameBrand() string {
	if x != nil {
		return x.GameBrand
	}
	return ""
}

func (x *VerifySlotOptWeightsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *VerifySlotOptWeightsRequest) GetRoundModel() string {
	if x != nil {
		return x.RoundModel
	}
	return ""
}

func (x *VerifySlotOptWeightsRequest) GetRtp() string {
	if x != nil {
		return x.Rtp
	}
	return ""
}

func (x *VerifySlotOptWeightsRequest) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

type VerifySlotOptWeightsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SlotOptWeightsState    `protobuf:"varint,1,opt,name=state,proto3,enum=rtp.v1.SlotOptWeightsState" json:"state,omitempty"` // 权重状态
	CacheKey      string                 `protobuf:"bytes,2,opt,name=cacheKey,proto3" json:"cacheKey,omitempty"`                            // Redis 权重缓存 key
	BaseTable     string                 `protobuf:"bytes,3,opt,name=baseTable,proto3" json:"baseTable,omitempty"`                          // 普通 spin 表名（ready 时有值）
	FsTable       string                 `protobuf:"bytes,4,opt,name=fsTable,proto3" json:"fsTable,omitempty"`                              // freespin 表名（ready 时有值，可为空）
	FsTrigger     float64                `protobuf:"fixed64,5,opt,name=fsTrigger,proto3" json:"fsTrigger,omitempty"`                        // freespin 触发概率（ready 时有值）
	BaseProbCount int32                  `protobuf:"varint,6,opt,name=baseProbCount,proto3" json:"baseProbCount,omitempty"`                 // 普通 spin 权重条目数
	FsProbCount   int32                  `protobuf:"varint,7,opt,name=fsProbCount,proto3" json:"fsProbCount,omitempty"`                     // freespin 权重条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySlotOptWeightsReply) Reset() {
	*x = VerifySlotOptWeightsReply{}
	mi := &file_rtp_v1_rtp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySlotOptWeightsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySlotOptWeightsReply) ProtoMessage() {}

func (x *VerifySlotOptWeightsReply) ProtoReflect() protoreflect.Message {
	mi := &file_rtp_v1_rtp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySlotOptWeightsReply.ProtoReflect.Descriptor instead.
func (*VerifySlotOptWeightsReply) Descriptor() ([]byte, []int) {
	return file_rtp_v1_rtp_proto_rawDescGZIP(), []int{13}
}

func (x *VerifySlotOptWeightsReply) GetState() SlotOptWeightsState {
	if x != nil {
		return x.State
	}
	return SlotOptWeightsState_SLOT_OPT_WEIGHTS_STATE_UNSPECIFIED
}

func (x *VerifySlotOptWeightsReply) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *VerifySlotOptWeightsReply) GetBaseTable() string {
	if x != nil {
		return x.BaseTable
	}
	return ""
}

func (x *VerifySlotOptWeightsReply) GetFsTable() string {
	if x != nil {
		return x.FsTable
	}
	return ""
}

func (x *VerifySlotOptWeightsReply) GetFsTrigger() float64 {
	if x != nil {
		return x.FsTrigger
	}
	return 0
}

func (x *VerifySlotOptWeightsReply) GetBaseProbCount() int32 {
	if x != nil {
		return x.BaseProbCount
	}
	return 0
}

func (x *VerifySlotOptWeightsReply) GetFsProbCount() int32 {
	if x != nil {
		return x.FsProbCount
	}
	return 0
}

var File_rtp_v1_rtp_proto protoreflect.FileDescriptor

const file_rtp_v1_rtp_proto_rawDesc = "" +
	"\n" +
	"\x10rtp/v1/rtp.proto\x12\x06rtp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x02\n" +
	"\x11SelectSpinRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1c\n" +
	"\tgameBrand\x18\x03 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\x12\x1f\n" +
	"\vround_model\x18\x06 \x01(\tR\n" +
	"roundModel\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x12\n" +
	"\x04mock\x18\b \x01(\tR\x04mock\x12&\n" +
	"\x0fround_ext_model\x18\t \x01(\tR\rroundExtModel\x12\x16\n" +
	"\x06spinId\x18\n" +
	" \x01(\x03R\x06spinId\x12$\n" +
	"\rspinTableName\x18\v \x01(\tR\rspinTableName\"\xfe\x02\n" +
	"\x0fSelectSpinReply\x12\x16\n" +
	"\x06spinId\x18\x01 \x01(\x03R\x06spinId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03bet\x18\x04 \x01(\x01R\x03bet\x12\x1c\n" +
	"\toriginBet\x18\x05 \x01(\x01R\toriginBet\x12&\n" +
	"\x0eoriginTotalWin\x18\x06 \x01(\x01R\x0eoriginTotalWin\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x1f\n" +
	"\vround_model\x18\b \x01(\tR\n" +
	"roundModel\x12\x1c\n" +
	"\ttableName\x18\t \x01(\tR\ttableName\x12\x10\n" +
	"\x03rtp\x18\n" +
	" \x01(\tR\x03rtp\x12\x12\n" +
	"\x04rate\x18\v \x01(\x01R\x04rate\x12\x1a\n" +
	"\bcompress\x18\f \x01(\x05R\bcompress\x12\x16\n" +
	"\x06nextId\x18\r \x01(\x03R\x06nextId\x12\x18\n" +
	"\agroupId\x18\x0e \x01(\tR\agroupId\"}\n" +
	"\x13GetPlayerRtpRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1c\n" +
	"\tgameBrand\x18\x03 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\tR\x06gameId\"%\n" +
	"\x11GetPlayerRtpReply\x12\x10\n" +
	"\x03rtp\x18\x01 \x01(\tR\x03rtp\"\x8f\x01\n" +
	"\x15GetBaccaratRtpRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x18\n" +
	"\aroundId\x18\x04 \x01(\tR\aroundId\x12\x10\n" +
	"\x03rtp\x18\x05 \x01(\tR\x03rtp\"S\n" +
	"\x13GetBaccaratRtpReply\x12\x10\n" +
	"\x03rtp\x18\x01 \x01(\tR\x03rtp\x12\x14\n" +
	"\x05rate1\x18\x02 \x01(\x01R\x05rate1\x12\x14\n" +
	"\x05rate2\x18\x03 \x01(\x01R\x05rate2\"\xe1\x01\n" +
	"\x15SettleBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12$\n" +
	"\rroundBetTotal\x18\x04 \x01(\x01R\rroundBetTotal\x12*\n" +
	"\x10roundProfitTotal\x18\x05 \x01(\x01R\x10roundProfitTotal\x12\x18\n" +
	"\aroundId\x18\x06 \x01(\tR\aroundId\x12\x10\n" +
	"\x03rtp\x18\a \x01(\tR\x03rtp\"\x15\n" +
	"\x13SettleBaccaratReply\"t\n" +
	"\x14ResetBaccaratRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tgameBrand\x18\x02 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\tR\x03rtp\"\x14\n" +
	"\x12ResetBaccaratReply\"\x99\x01\n" +
	"\x1cRefreshSlotOptWeightsRequest\x12\x1c\n" +
	"\tgameBrand\x18\x01 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vround_model\x18\x03 \x01(\tR\n" +
	"roundModel\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\tR\x03rtp\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\"8\n" +
	"\x1aRefreshSlotOptWeightsReply\x12\x1a\n" +
	"\bcacheKey\x18\x01 \x01(\tR\bcacheKey\"\x98\x01\n" +
	"\x1bVerifySlotOptWeightsRequest\x12\x1c\n" +
	"\tgameBrand\x18\x01 \x01(\tR\tgameBrand\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vround_model\x18\x03 \x01(\tR\n" +
	"roundModel\x12\x10\n" +
	"\x03rtp\x18\x04 \x01(\tR\x03rtp\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x01R\x03bet\"\x88\x02\n" +
	"\x19VerifySlotOptWeightsReply\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.rtp.v1.SlotOptWeightsStateR\x05state\x12\x1a\n" +
	"\bcacheKey\x18\x02 \x01(\tR\bcacheKey\x12\x1c\n" +
	"\tbaseTable\x18\x03 \x01(\tR\tbaseTable\x12\x18\n" +
	"\afsTable\x18\x04 \x01(\tR\afsTable\x12\x1c\n" +
	"\tfsTrigger\x18\x05 \x01(\x01R\tfsTrigger\x12$\n" +
	"\rbaseProbCount\x18\x06 \x01(\x05R\rbaseProbCount\x12 \n" +
	"\vfsProbCount\x18\a \x01(\x05R\vfsProbCount*\xaa\x01\n" +
	"\x13SlotOptWeightsState\x12&\n" +
	"\"SLOT_OPT_WEIGHTS_STATE_UNSPECIFIED\x10\x00\x12$\n" +
	" SLOT_OPT_WEIGHTS_STATE_NOT_FOUND\x10\x01\x12#\n" +
	"\x1fSLOT_OPT_WEIGHTS_STATE_TRAINING\x10\x02\x12 \n" +
	"\x1cSLOT_OPT_WEIGHTS_STATE_READY\x10\x032\xbc\x04\n" +
	"\x06RtpApi\x12@\n" +
	"\n" +
	"SelectSpin\x12\x19.rtp.v1.SelectSpinRequest\x1a\x17.rtp.v1.SelectSpinReply\x12F\n" +
	"\fGetPlayerRtp\x12\x1b.rtp.v1.GetPlayerRtpRequest\x1a\x19.rtp.v1.GetPlayerRtpReply\x12L\n" +
	"\x0eGetBaccaratRtp\x12\x1d.rtp.v1.GetBaccaratRtpRequest\x1a\x1b.rtp.v1.GetBaccaratRtpReply\x12L\n" +
	"\x0eSettleBaccarat\x12\x1d.rtp.v1.SettleBaccaratRequest\x1a\x1b.rtp.v1.SettleBaccaratReply\x12I\n" +
	"\rResetBaccarat\x12\x1c.rtp.v1.ResetBaccaratRequest\x1a\x1a.rtp.v1.ResetBaccaratReply\x12a\n" +
	"\x15RefreshSlotOptWeights\x12$.rtp.v1.RefreshSlotOptWeightsRequest\x1a\".rtp.v1.RefreshSlotOptWeightsReply\x12^\n" +
	"\x14VerifySlotOptWeights\x12#.rtp.v1.VerifySlotOptWeightsRequest\x1a!.rtp.v1.VerifySlotOptWeightsReplyBO\n" +
	"\x15dev.kratos.api.rtp.v1B\n" +
	"RtpProtoV1P\x01Z(github.com/apexkit/gamekit/api/rtp/v1;v1b\x06proto3"

var (
	file_rtp_v1_rtp_proto_rawDescOnce sync.Once
	file_rtp_v1_rtp_proto_rawDescData []byte
)

func file_rtp_v1_rtp_proto_rawDescGZIP() []byte {
	file_rtp_v1_rtp_proto_rawDescOnce.Do(func() {
		file_rtp_v1_rtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rtp_v1_rtp_proto_rawDesc), len(file_rtp_v1_rtp_proto_rawDesc)))
	})
	return file_rtp_v1_rtp_proto_rawDescData
}

var file_rtp_v1_rtp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rtp_v1_rtp_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rtp_v1_rtp_proto_goTypes = []any{
	(SlotOptWeightsState)(0),             // 0: rtp.v1.SlotOptWeightsState
	(*SelectSpinRequest)(nil),            // 1: rtp.v1.SelectSpinRequest
	(*SelectSpinReply)(nil),              // 2: rtp.v1.SelectSpinReply
	(*GetPlayerRtpRequest)(nil),          // 3: rtp.v1.GetPlayerRtpRequest
	(*GetPlayerRtpReply)(nil),            // 4: rtp.v1.GetPlayerRtpReply
	(*GetBaccaratRtpRequest)(nil),        // 5: rtp.v1.GetBaccaratRtpRequest
	(*GetBaccaratRtpReply)(nil),          // 6: rtp.v1.GetBaccaratRtpReply
	(*SettleBaccaratRequest)(nil),        // 7: rtp.v1.SettleBaccaratRequest
	(*SettleBaccaratReply)(nil),          // 8: rtp.v1.SettleBaccaratReply
	(*ResetBaccaratRequest)(nil),         // 9: rtp.v1.ResetBaccaratRequest
	(*ResetBaccaratReply)(nil),           // 10: rtp.v1.ResetBaccaratReply
	(*RefreshSlotOptWeightsRequest)(nil), // 11: rtp.v1.RefreshSlotOptWeightsRequest
	(*RefreshSlotOptWeightsReply)(nil),   // 12: rtp.v1.RefreshSlotOptWeightsReply
	(*VerifySlotOptWeightsRequest)(nil),  // 13: rtp.v1.VerifySlotOptWeightsRequest
	(*VerifySlotOptWeightsReply)(nil),    // 14: rtp.v1.VerifySlotOptWeightsReply
}
var file_rtp_v1_rtp_proto_depIdxs = []int32{
	0,  // 0: rtp.v1.VerifySlotOptWeightsReply.state:type_name -> rtp.v1.SlotOptWeightsState
	1,  // 1: rtp.v1.RtpApi.SelectSpin:input_type -> rtp.v1.SelectSpinRequest
	3,  // 2: rtp.v1.RtpApi.GetPlayerRtp:input_type -> rtp.v1.GetPlayerRtpRequest
	5,  // 3: rtp.v1.RtpApi.GetBaccaratRtp:input_type -> rtp.v1.GetBaccaratRtpRequest
	7,  // 4: rtp.v1.RtpApi.SettleBaccarat:input_type -> rtp.v1.SettleBaccaratRequest
	9,  // 5: rtp.v1.RtpApi.ResetBaccarat:input_type -> rtp.v1.ResetBaccaratRequest
	11, // 6: rtp.v1.RtpApi.RefreshSlotOptWeights:input_type -> rtp.v1.RefreshSlotOptWeightsRequest
	13, // 7: rtp.v1.RtpApi.VerifySlotOptWeights:input_type -> rtp.v1.VerifySlotOptWeightsRequest
	2,  // 8: rtp.v1.RtpApi.SelectSpin:output_type -> rtp.v1.SelectSpinReply
	4,  // 9: rtp.v1.RtpApi.GetPlayerRtp:output_type -> rtp.v1.GetPlayerRtpReply
	6,  // 10: rtp.v1.RtpApi.GetBaccaratRtp:output_type -> rtp.v1.GetBaccaratRtpReply
	8,  // 11: rtp.v1.RtpApi.SettleBaccarat:output_type -> rtp.v1.SettleBaccaratReply
	10, // 12: rtp.v1.RtpApi.ResetBaccarat:output_type -> rtp.v1.ResetBaccaratReply
	12, // 13: rtp.v1.RtpApi.RefreshSlotOptWeights:output_type -> rtp.v1.RefreshSlotOptWeightsReply
	14, // 14: rtp.v1.RtpApi.VerifySlotOptWeights:output_type -> rtp.v1.VerifySlotOptWeightsReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rtp_v1_rtp_proto_init() }
func file_rtp_v1_rtp_proto_init() {
	if File_rtp_v1_rtp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rtp_v1_rtp_proto_rawDesc), len(file_rtp_v1_rtp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtp_v1_rtp_proto_goTypes,
		DependencyIndexes: file_rtp_v1_rtp_proto_depIdxs,
		EnumInfos:         file_rtp_v1_rtp_proto_enumTypes,
		MessageInfos:      file_rtp_v1_rtp_proto_msgTypes,
	}.Build()
	File_rtp_v1_rtp_proto = out.File
	file_rtp_v1_rtp_proto_goTypes = nil
	file_rtp_v1_rtp_proto_depIdxs = nil
}
